name: check-journal
version: '1.1.3-dev'
summary: Nagios/Icinga compatible plugin for journalctl
description: Nagios/Icinga compatible plugin to search `journalctl` output for matching lines
grade: stable
confinement: strict

base: core18

apps:
  check-journal:
    command: usr/bin/check_journal

parts:
  check-journal:
    source: .
    plugin: make
    make-parameters:
      - PREFIX=/usr
    build-packages:
      - cargo
      - ruby-ronn
